---
- name: Install and setup a datastax cassandra node on rhel7
  hosts: cassandra
  vars_files:
    - vars/vars.yml
  gather_facts: True

  tasks:
    # Displaying all variables/facts known for host {{ inventory_hostname }}
    #- debug: var=hostvars[inventory_hostname]
    - debug: var=hostvars[inventory_hostname]['ansible_enp0s3']['ipv4']['address']
    #- debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

    # Copy elastic repository file in /etc/yum.repos.d
    - copy:
        src: files/dtx-cassandra.repo
        dest: /etc/yum.repos.d/dtx-cassandra.repo
        owner: root
        group: root
        mode: 0644
        backup: yes
      become: true


    # read the new repository file
    - command: /usr/bin/yum clean expire-cache
      become: true
    - command: /usr/bin/yum repolist
      become: true

    # ## java install ## #
    - name: download Oracle JDK check (md5)
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.rpm
    #   url=http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.rpm
        dest: /tmp/jdk-linux-x64.rpm
        headers: 'Cookie:gpw_e24=xxx; oraclelicense=accept-securebackup-cookie'
        checksum: md5:353403dbc633d70e527f7a8fc9cb708e
    #    checksum: {{ jdk_checksum_md5 }}

    - name: Install jdk-linux rpm package.
      yum:
         name: /tmp/jdk-linux-x64.rpm
         state: present
      become: true

    # Create user and group with proper uid/gid
    - group:
        name: cassandra
        state: present
        gid: 42000
      become: true
    - user:
        name: cassandra
        #comment: "Datastax cassandra user"
        uid: 42000
        groups: cassandra
        append: yes
      become: true

    # Create the sysctld. cassandra file from template
    - template:
        src: files/sysctl.d.cassandra.conf
        dest: /etc/sysctl.d/cassandra.conf
        owner: root
        group: root
        mode: "u=rw,g=rw,o=r"
        force: true
      become: true

    # Install packages
    - name: Install desired packages
      yum: >
        package={{ item }}
        state=present
      with_items:
        - dsc30
        - cassandra30-tools
        - python-cassandra-driver.x86_64
        - ntp
      become: true

    # Create the cassandra.yaml file from template
    - template:
        src: files/cassandra.yaml.j2
        dest: /etc/cassandra/default.conf/cassandra.yaml
        owner: cassandra
        group: cassandra
        mode: "u=rwx,g=rx,o=rx"
        force: true
      become: true
    # Create the cassandra-env.sh file from template
    - template:
        src: files/cassandra-env.sh.j2
        dest: /etc/cassandra/default.conf/cassandra-env.sh
        owner: cassandra
        group: cassandra
        mode: "u=rwx,g=rx,o=rx"
        force: true
      become: true
    # Create the cassandra-rackdc.properties file from template
    - template:
        src: files/cassandra-rackdc.properties.j2
        dest: /etc/cassandra/default.conf/cassandra-rackdc.properties
        owner: cassandra
        group: cassandra
        mode: "u=rwx,g=rx,o=rx"
        force: true
      become: true

    # Create the ntp.conf file
    - copy:
        src: files/ntp.conf
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
        force: true
      become: true
      tags:
        - configuration

    # start the ntpd service
    - systemd:
        name: ntpd
        state: started
      become: true
    # enable ntpd service @boot
    - systemd:
        name: ntpd
        enabled: yes
      become: true

    # start the cassandra service
    - systemd:
        name: cassandra
        state: started
      become: true
    # enable cassandra service @boot
    - systemd:
        name: cassandra
        enabled: yes
      become: true
